{{- if not .Values.externalConfig.secretRef.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.fullname" . }}-config
data:
  config.yml: {{ toYaml .Values.config | b64enc }}
{{- end }}
